version: '2'
services:
    be4techapp-app:
        image: be4techapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://be4techapp-postgresql:5432/be4techApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://be4techapp-elasticsearch:9200
        ports:
            - 8080:8080
    be4techapp-postgresql:
        extends:
            file: postgresql.yml
            service: be4techapp-postgresql
    be4techapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: be4techapp-elasticsearch
